<?php
/**
 * PrivilegeAction
 *
 * This class has been auto-generated by the CI Framework
 *
 * @package    CodeIgniter
 * @subpackage libraries
 * @author     Otávio Fernandes <otavio@neton.com.br>
 * @version    SVN: $Id:
 */
class PrivilegeAction extends autoPrivilegeAction
{
  /**
   * Campos e relacionamentos do modelo que serão auto-selecionados pela função
   * index.
   *
   * @access public
   * @var array
   */
  public $autoSelections = array(
    'fields' => array('c.*'),
    'relations' => array()
  );

  /**
   * @remotable
   */
  public function teste($request)
  {
    return $request;
  }
}