<?php
/**
 * UserAction
 *
 * This class has been auto-generated by the CI Framework
 *
 * @package    CodeIgniter
 * @subpackage libraries
 * @author     Otávio Fernandes <otavio@neton.com.br>
 * @version    SVN: $Id:
 */
class UserAction extends autoUserAction
{
  /**
   * Campos e relacionamentos do modelo que serão auto-selecionados pela função
   * index.
   *
   * @access public
   * @var array
   */
  public $autoSelections = array(
    'fields' => array('c.*','g.name as group'),
    'relations' => array('Group' => 'g')
  );

  /**
   * Nome da classe módulo na UI.
   *
   * @var string
   */
  public $basePermission = 'user';

  /**
   * Verifica se existe uma sessão aberta para o usuário.
   *
   * @remotable
   * 
   * @param array $request Parâmetros enviados para a requisição
   */
  public function checkSession($request)
  {
    $user = new User();

    return $user->checkSession();
  }

  /**
   * @remotable
   */
  public function teste($request)
  {
    return "Teste";
  }
  
  /**
   * Faz a requisição de autenticação de um usuário
   *
   * @remotable
   * 
   * @param array $request Parâmetros enviados pela requisição
   */
  public function requestLogon($request)
  {
    // instância o modelo
    $user = new User();

    // retorna o resultado da autenticação do usuário
    return $user->authenticate($request['data']);
  }

  /**
   * Faz a requisição de remoção da sessão do usuário.
   *
   * @remotable
   *
   * @param array $request Parâmetros enviados pela requisição
   */
  public function requestLogout($request)
  {
    $user = new User();
    
    return $user->logout();
  }

  /**
   * Lista todos os técnicos do sistema.
   * 
   * @remotable
   */
  public function listTecnicos($request)
  {
    return $this->index($request);
  }
}