/*
 * File: Login.ui.js
 * Date: Mon Apr 05 2010 13:38:37 GMT-0300 (Hora oficial do Brasil)
 * 
 * This file was generated by Ext Designer version xds-1.0.0.6.
 * http://www.extjs.com/products/designer/
 *
 * This file was manually exported.
 */

var LoginUi = Ext.extend(Ext.Window, {
    title: 'Acesso restrito',
    width: 301,
    height: 180,
    layout: 'hbox',
    bodyStyle: 'padding:8px;',
    accessButtonText: '<b>Acessar</b>',
    clearButtonText: 'Limpar',
    loginFieldLabel: 'Usu&aacute;rio',
    waitingLogonText: 'Verificando...',
    passFieldLabel: 'Senha',
    closable: false,
    initComponent: function() {
        this.fbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: this.accessButtonText,
                    itemId: 'accessButton',
                    handler: this.module.requestLogon,
                    scope: this.module,
                    plugins: [new Wow.Mask({waitingText: this.waitingLogonText, itemId: 'mask'})]
                },
                {
                    xtype: 'button',
                    text: this.clearButtonText,
                    itemId: 'clearButton',
                    handler: this.module.clear,
                    scope: this.module                    
                }
            ]
        };
        this.items = [
            {
                xtype: 'container',
                autoEl: 'div',
                width: 180,
                itemId: 'container',
                items: [
                    {
                        xtype: 'form',
                        labelWidth: 100,
                        labelAlign: 'top',
                        autoHeight: true,
                        layout: 'form',
                        itemId: 'form',
                        baseCls: 'x-plain',
                        items: [
                            {
                                xtype: 'textfield',
                                fieldLabel: this.loginFieldLabel,
                                anchor: '100%',
                                allowBlank: false,
                                itemId: 'login',
                                name: 'login'
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: this.passFieldLabel,
                                anchor: '100%',
                                allowBlank: false,
                                itemId: 'pass',
                                inputType: 'password',
                                name: 'pass',
                                enableKeyEvents: true,
                                listeners:{
                                    'keyup' : function(field, event){
                                        if (event.getKey() == 13){
                                            this.module.requestLogon();
                                        }

                                    },
                                    scope: this
                                }
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                autoEl: 'div',
                width: 120,
                html: '<img src="images/lock.png" style="margin-left:10px;"/>'
            }
        ];
        LoginUi.superclass.initComponent.call(this);
    },

    afterRender : function(){
        LoginUi.superclass.afterRender.apply(this);
        this.form = this.getComponent('container').getComponent('form');
        this.accessButton = this.fbar.getComponent('accessButton');
        this.clearButton = this.fbar.getComponent('clearButton');
    }
});
