<?php

/**
 * Group
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Group extends BaseGroup
{
  /**
   * Retorna a lista de privilégios de um determinado grupo de usuários.
   *
   * @return array
   */
  public function getPrivileges()
  {
    $list = array();

    foreach ($this->Privilege as $priv)
    {
      $list[$priv->Permission->name] = true;
    }

    return $list;
  }


}