<?php

/**
 * ModuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModuleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Module');
    }
}