<?php

/**
 * PrivilegeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrivilegeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrivilegeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Privilege');
    }
}