<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{    
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }

    /**
     * Verifica se um usuário existe pelo seu usuário e senha
     *
     * @param string $login Login do usuário
     * @param string $pass  Senha do usuário
     *
     * @return Mixed[Boolean/Doctrine_Record] 
     */
    public function findByLoginPass($login, $pass)
    {
      // cria a consulta dql
      $q = Doctrine_Query::create()
            ->select('*')
            ->from('User')
            ->where('login = ? and pass = ? and active = ?', array($login, md5($pass),'1'));

      // executa a consulta
      $rs = $q->execute();

      // se o registro existir
      if ($rs)
      {
        // rertona o primeiro registro (único)
        $rs = $rs->getFirst();
      }

      return $rs;
    }
}