/*
 * File: GroupStore.js
 * Date: Tue Aug 17 2010 21:53:40 GMT-0300 (Hora oficial do Brasil)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.11.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

GroupStore = Ext.extend(Ext.data.DirectStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        GroupStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'GroupStore',
            root: 'records',
            directFn: Ext.app.Group.index,
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'name'
                }
            ]
        }, cfg));
    }
});
Ext.reg('group-store', GroupStore);new GroupStore();