/*
 * File: UserForm.ui.js
 * Date: Tue Aug 17 2010 21:53:40 GMT-0300 (Hora oficial do Brasil)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.11.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

UserFormUi = Ext.extend(Ext.form.FormPanel, {
    width: 400,
    height: 250,
    padding: 10,
    border: false,
    autoHeight: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Nome',
                anchor: '100%',
                name: 'fullname',
                allowBlank: false
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Login',
                anchor: '100%',
                name: 'login',
                allowBlank: false
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Senha',
                anchor: '100%',
                name: 'pass',
                allowBlank: false,
                inputType: 'password'
            },
            {
                xtype: 'combo',
                fieldLabel: 'Grupo',
                anchor: '100%',
                hiddenName: 'group_id',
                name: 'group_id',
                displayField: 'name',
                valueField: 'id',
                triggerAction: 'all',
                store: 'GroupStore',
                ref: 'cmbGrupo'
            },
            {
                xtype: 'checkbox',
                fieldLabel: 'Label',
                boxLabel: 'Este usuário está ativo',
                anchor: '100%',
                hideLabel: true,
                name: 'active',
                ref: 'ckActive'
            }
        ];
        UserFormUi.superclass.initComponent.call(this);
    }
});
