/*
 * File: UserForm.js
 * Date: Thu Jul 29 2010 11:27:19 GMT-0300 (Hora oficial do Brasil)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.11.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

UserForm = Ext.extend(UserFormUi, {
    initComponent: function() {
        UserForm.superclass.initComponent.call(this);
        
        this.ckActive.replaceWith({xtype: 'xcheckbox'});
        this.cmbGrupo.replaceWith({xtype: 'xcombo'});
    }
});
Ext.reg('user-form', UserForm);